### ISSUE TITLE
Is this Max 2021 only?

### ISSUE THREAD

**Issue by Elwood89** [ShirzadBh/posture#1]
Hello, I' trying to test the plugin on Max 2020, it says:
1. "syntax error" for the python 3.7 version
2.  "ImportError: No module named qtmax" for the python 2.7 version
Must we update to 2021 to use the script?

**Comment by ShirzadBh** [comment]
For now yes, but I'll try to write it for 2017 - 2020 as well, it should not take too long, because it's just about UI.

**Comment by ShirzadBh** [comment]
Check the beta version for 2019 and 2020

**Comment by Elwood89** [comment]
Tested the beta in 2020, seems to be working OK with CAT. Thank you very much!
One more thing - the help says that we can save a "Node with children", but to save, say, a hand with all fingers, I must select both the top node (hand) and all the children? There is no option to save an entire hierarchy starting from the selected (added) object?

**Comment by ShirzadBh** [comment]
>There is no option to save an entire hierarchy starting from the selected (added) object?

Cool Idea! I'll try to add this option in the next version.
